### ISSUE TITLE
Does it work on Linux (Ubuntu)?

### ISSUE THREAD

**Issue by mrroot5** [alemonteiro/brackets-sql-connector#1]
Hello,

I have Ubuntu 14.04 but i don't know how to use your extension. I do the npm install on your extension node folder and reload Brackets but it still doesn't work.

This is my brackets right side:
![brackets-right-side](https://cloud.githubusercontent.com/assets/1659540/14102219/1a5b2c0e-f591-11e5-918e-d946404ca363.png)

Do you have any suggestion?

Thank you very much :)

**Comment by alemonteiro** [comment]
I didn't test it on linux, but i guess it should... it's probably a bug on my code =x

The extension is somewhat loaded, on the bottom panel you can see "Not Connected", if you click there you should be able to open an menu and manage your connection throw there.

I'm gonna check about the right pane icon, and if you could see if there's any errors on your brackets console (F12) it could speed things up =) It's probably something on /brackets-sql-connector/main.js

**Comment by mrroot5** [comment]
Whne you click in Not Connected don't show nothing and throw this error:
Uncaught TypeError: Cannot read property 'servers' of undefined
main.js - 121

Maybe, node didn't install properly, I didn't see errors when i do npm install in your extension folder :S.

**Comment by alemonteiro** [comment]
Thanks for the feedback. Gonna update an fix in a few =)

**Comment by mrroot5** [comment]
Ok, thank you. If you need something more tell me ;). I will test your new fix asap.

**Comment by alemonteiro** [comment]
v 0.3.2 It's up 
There's probably a lot more of bugs, but those two are gone, I hope! =)

**Comment by mrroot5** [comment]
It works!! But I can't testing it now :(. I will give you more feedback in a couple of hours or maybe tomorrow :).

**Comment by alemonteiro** [comment]
Glad to know!
Any feedback is welcome =)
I gotta do some work, but i like playing with this so much that I'll probably release some update latter
