### ISSUE TITLE
Cannot find module 'mysql'

### ISSUE THREAD

**Issue by tanguyvda** [alemonteiro/brackets-sql-connector#2]
Hi,

I had some trouble with the size of the result panel. It took all the editor space and couldn't resize it to make it show my editor panel. By the way, I've found out that there was an update so I did it and now here is what happen : 

Error loading domain "BracketsSqlConnectorDomain": Unable to load one of the modules: C:/Users/tcharles/AppData/Roaming/Brackets/extensions/user/brackets-sql-connector/node/SQLConnectorDomain, reason: Cannot find module 'mysql

and 

Resizable panels within the editor area should be created via WorkspaceManager.createBottomPanel(). 
Element: n.fn.init[1]0: div#brackets-sql-connector-result-pane.brackets-sql-connector-result-panelength: 1__proto__: n[0]/utils/Resizer.js:239 makeResizable

Regards

Tanguy

**Comment by azlux** [comment]
Same here for the module error (unable to load) since the last update

**Comment by alemonteiro** [comment]
Sorry guys, my bad on last update, forgot to put the modules in, gonna upload a fix in a few.
A fix until:
$ npm install
on the node folder.

And strange that about the pane size, i do use createBottomPane for the resizable editor, but gonna check it.

**Comment by alemonteiro** [comment]
I'm unable to upload the new version on brackets extension registry, seems to be a issue on the registry:
https://github.com/adobe/brackets/issues/7387

For now you need to run **npm install** on the node folder or download and extract to the extension folder: http://alemonteiro.com.br/brackets-sql-connector.zip

@tanguyvda  I added an max-height to the result panel on 0.5.2, let me know if it fixes your issue.

**Comment by tanguyvda** [comment]
both of the issues are now fixed, thanks to you. I open a new ticket for the last problem that I face.

**Comment by alemonteiro** [comment]
glad to know =)
