### ISSUE TITLE
standard color

### ISSUE THREAD

**Issue by IgorNovozhilov** [alemonteiro/brackets-sql-connector#4]
Maybe you should use a standard color? Or to inherit styles from themes?
Otherwise, in most cases, we can't see.

![2016-04-13_08h56_41](https://cloud.githubusercontent.com/assets/3082812/14484066/154f0430-0156-11e6-800e-7ce5c5738e9b.png)

---

(translate.yandex.ru)

**Comment by IgorNovozhilov** [comment]
You need to use the "dark" modifier, for all containers.

![2016-04-13_09h20_27](https://cloud.githubusercontent.com/assets/3082812/14484448/3ee92f02-0159-11e6-8a9b-8680f7977500.png)

---

(translate.yandex.ru)

**Comment by IgorNovozhilov** [comment]
Perhaps I'll look into it :bulb:
https://github.com/iNovozhilov/brackets-sql-connector/tree/bugfix/standard-color

---

(translate.yandex.ru)

**Comment by alemonteiro** [comment]
Oh sorry, my bad. I'm so into dark colors that I never tested with the default colors or any other color scheme.

Feel free to fix it and pull. 

In the mean time I'll also take a look at this so I can learn about it.

**Comment by alemonteiro** [comment]
@iNovozhilov, i just commited an quick fix about the colors. But I can't upload the new version to the brackets extension registry yet.
I'm looking forward to your auto-install fix, it will solve this once and for all =)

About the colors, I just added 'panel' and 'dark' classes to both panels as you suggested and then removed all colors and background-colors from the extension css.
Seems to be the same on both light and dark themes now.

**Comment by alemonteiro** [comment]
Just uploaded the merged version with auto install and color fixes.
Let me know if it's all ok.

**Comment by IgorNovozhilov** [comment]
Well done, the text can now be read :ok_hand: 

---

(translate.yandex.ru)
