### ISSUE TITLE
Can't select items in menu

### ISSUE THREAD

**Issue by tanguyvda** [alemonteiro/brackets-sql-connector#8]
Hi !

Since last update, we have now those menu that shows up on mouse over but I can't use them  :< 

When my mouse is on its way to select my server for example, it just vanishes. see picture below

http://i.imgur.com/EmcnF5R.png
http://i.imgur.com/JApAn0a.png
http://i.imgur.com/2HS2dEN.png

the red dot indicates where my mouse is when I take the screenshot

**Comment by alemonteiro** [comment]
Fixed on 0.5.8.

it was a silly mistake on last minute change =x

**Comment by tanguyvda** [comment]
Haha, the famous last minute change :). I used your patch, it works fine. Great job !

**Comment by alemonteiro** [comment]
I have some tick about it, I just can't resist to change some times! lol ^^
